env: local
app:
  name: demo
  version: 0.0.1

http:
  host: 0.0.0.0
  port: 8080

security:
  api_sign:
    app_key: 123456
    app_security: 123456
  jwt:
    key: QQYnRFerJTSEcrfB89fw8prOaObmrch8

database:
  driver: mysql
  dsn: root:12345678@tcp(127.0.0.1:13306)/oai?charset=utf8mb4&parseTime=True&loc=Local
#  driver: sqlite
#  dsn: storage/oai.db?_busy_timeout=5000
#  driver: postgres
#  dsn: host=localhost user=gorm password=gorm dbname=gorm port=9920 sslmode=disable TimeZone=Asia/Shanghai


#redis:
#  addr: 127.0.0.1:6350
#  password: ""
#  db: 0
#  read_timeout: 0.2s
#  write_timeout: 0.2s

log:
  log_level: debug
  encoding: json           # json or console
  log_path: "./data/logs"
  error_log_name: "error.log"
  log_file_name: "server.log"
  max_backups: 30
  max_age: 7
  max_size: 1024
  compress: true