// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/jiu-u/oai-api/internal/repository"
	"github.com/jiu-u/oai-api/internal/server"
	"github.com/jiu-u/oai-api/pkg/app"
	"github.com/jiu-u/oai-api/pkg/config"
	"github.com/jiu-u/oai-api/pkg/log"
)

// Injectors from wire.go:

func NewWire(cfg *config.Config, logger *log.Logger) (*app.App, func(), error) {
	db := repository.NewDB(cfg)
	migrate := server.NewMigrate(db, logger)
	appApp := newApp(migrate)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction)

var serverSet = wire.NewSet(server.NewMigrate)

// build App
func newApp(
	migrateServer *server.Migrate,

) *app.App {
	return app.NewApp(app.WithServer(migrateServer), app.WithName("demo-server"))
}
